sudo: required
language: bash
services:
  - docker
before_install:
  - make
script:
  - docker-compose up -d postgres
  - sleep 10
  - docker-compose run import-naturalearth
  - docker-compose run db-schema
  - docker-compose run -e "BBOX=5.8559113 45.717995 10.5922941 47.9084648" export-vectortiles
